# Server
server.port=8080

# Application
spring.application.name=traffic-vision

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/traffic-vision-db
spring.datasource.username=postgres
spring.datasource.password=root123
spring.datasource.driverClassName=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# File upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# JWT
jwt.secret=dHJhZmZpYy12aXNpb24tc3VwZXItc2VjcmV0LWp3dC1rZXktZm9yLWhzMjU2
jwt.expiration=86400000

# Python API
python.api.url=http://localhost:5000

# File storage
file.upload.dir=./uploads

# CORS
cors.allowed-origins=http://localhost:3000

# Devtools (development uchun)
spring.devtools.restart.enabled=true

# Logging
logging.level.uz.pdp.trafficvision=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Cloud config off
spring.cloud.config.enabled=false
